# Site settings
title: CM - Web Development
author: Cipriano Mazzieri. CM - Web Development
email: cmazzieri@gmail.com
description: > #"baseurl:"
  CM - Web Development is a web development studio focused on creating simple, nice looking and fast websites.
baseurl: ""
url: "http://localhost:4000"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
