# Site settings
title: CM - Web Development
author: Cipriano Mazzieri. CM - Web Development
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  CM - Web Development is a web development studio focused on creating simple, nice looking and fast websites.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
